rested: 
  pos: 
    - 176
    - 58
  color: 0x9FBE40
fatigued: 
  pos: 
    - 7
    - 64
  color: 0x211C17
idle: 
  pos: 
    - 1081
    - 907
  color: 0x232321
busy: 
  pos: 
    - 1081
    - 907
  color: 0x6C90A3